-- Seed script to populate new Supabase project database (Exact schema matching)

-- 1. PRODUCTS (24 products)
INSERT INTO public.products (id, category, subcategory, name, price, description, portions, img, status, min_qty, has_message, has_inner_message, has_edible_printing, individual_packaging, bows, is_full_width, options, flavours, spreads, created_at)
VALUES
('brownies-box', 'Brownies', NULL, 'Signature Brownies Box', '€32', 'Rich chocolate brownies with your choice of up to 3 signature spreads.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/brownies/brownie.webp', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Classic Chocolate']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c-3d', 'Cakes', NULL, '3D Custom Cake Designer', 'WA', 'Design your own cake in 3D! Choose layers, shapes, and decorations to see your masterpiece come to life.', NULL, NULL, 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c1', 'Cakes', NULL, '6 inch, 2 Layer (Round)', '€45', 'Serves ~10. Classic round cake. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 10', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-c1-1781039240493.webp?t=1781039242148', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, '[]'::jsonb, '{}'::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c2', 'Cakes', NULL, '6 inch, 2 Layer (Heart)', '€50', 'Serves ~10. Elegant heart-shaped design. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 10', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cakes/heart/heart-(1).webp', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c3', 'Cakes', NULL, '8 inch, 2 Layer (Round)', '€65', 'Serves ~20 - 25. Perfect for celebrations. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 20 - 25', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cakes/round/round-(2).webp', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c4', 'Cakes', NULL, '8 inch, 2 Layer (Heart)', '€72', 'Serves ~20 - 25. Show extra love with a large heart shape. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 20 - 25', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cakes/heart/heart-(2).webp', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c5', 'Cakes', NULL, '8 inch, 3 Layer (Round)', '€85', 'Serves ~ 30 - 38. Grand 3-layer masterpiece. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 30 - 38', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cakes/round/round-(11).webp', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('c7', 'Cakes', NULL, '8 inch, 3 Layer (Heart)', '€95', 'Serves ~ 30 - 38. Tall and impressive heart-shaped cake. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 30 - 38', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cakes/heart/heart-(3).webp', 'In Stock', 1, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cakesicles-bulk', 'Cakesicles', NULL, 'Additional Cakesicles', '€2.60', 'Add extra cakesicles to your order. Tiered pricing available for bulk orders.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cake-sicles/cakesicles-(4).webp', 'In Stock', 1, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cp1', 'Cake Pops', NULL, 'Cake Pops (Each)', '€1.70', 'Delicious cake pops (minimum order 15). Choice of Chocolate, Vanilla, or Red Velvet flavors.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cake-pops/pops-(1).webp', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cp2', 'Cake Pops', NULL, 'Cake Pops (Pack of 15)', '€25.50', 'A standard pack of 15 cake pops. Perfect for small gatherings. Choice of flavors.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cake-pops/pops-(2).webp', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cp3', 'Cake Pops', NULL, 'Cake Pops (Pack of 30)', '€51.00', 'A large pack of 30 cake pops for parties. Choice of Chocolate, Vanilla, or Red Velvet.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cake-pops/pops-(3).webp', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cu1', 'Cupcakes', 'Buttercream', 'Buttercream (Box of 6)', '€15', 'A half-dozen of our fluffiest buttercream cupcakes. Choice of flavors.', '', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-cu1-1781612066880.webp?t=1781612069213', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cu2', 'Cupcakes', 'Buttercream', 'Buttercream (Box of 12)', '€28.80', 'A full dozen premium buttercream cupcakes. Choice of flavors.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cupcakes/butter2.webp', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cu3', 'Cupcakes', 'Buttercream', 'Buttercream (Additional)', '€2.20', 'Add an individual buttercream cupcake to your order. Choice of flavors.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cupcakes/butter3.webp', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cu4', 'Cupcakes', 'White Chocolate', 'White Chocolate (Box of 6)', '€17', 'A half-dozen decadent white chocolate cupcakes. Choice of flavors.', '', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-cu4-1781629809229.webp?t=1781629821242', 'In Stock', 1, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cu5', 'Cupcakes', 'White Chocolate', 'White Chocolate (Box of 12)', '€32.50', 'A full dozen premium white chocolate cupcakes. Choice of flavors.', '', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-cu5-1781862499787.webp?t=1781862501404', 'In Stock', 1, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('cu6', 'Cupcakes', 'White Chocolate', 'White Chocolate (Additional)', '€2.50', 'Add an individual white chocolate cupcake to your order. Choice of flavors.', '', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-cu6-1781630115744.webp?t=1781630117992', 'In Stock', 1, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('mc1', 'Mini Cakes', NULL, 'Mini Cake (Small)', '€3.50', 'Bite-sized indulgence (Single portion). Choice of Chocolate, Vanilla, or Red Velvet flavors. Choice of 1 signature spread.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/minicakes/2.webp', 'In Stock', 4, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Chocolate', 'Vanilla', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('mc2', 'Mini Cakes', NULL, 'Mini Cake (Large)', '€5.50', 'A delightful small treat (Large portion). Choice of Chocolate, Vanilla, or Red Velvet flavors. Choice of 1 signature spread.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/minicakes/1.webp', 'In Stock', 4, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Chocolate', 'Vanilla', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder']::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('prod_v1s6bcz9', 'Cakes', NULL, '6 Inch 3 Layer', '€', 'Serves ~15 - 18. Classic round cake. Choice of Chocolate, Vanilla, or Red Velvet flavors.', 'Serves 15 - 18', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-prod_v1s6bcz9-1781612982675.webp?t=1781612983827', 'In Stock', 1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], ARRAY['Nutella', 'Biscoff', 'Pistachio', 'Kinder', 'White Chocolate', 'Ferrero Rocher']::text[], '2026-06-15T09:39:11.732+00:00'::timestamp with time zone),
('t2', 'Breakable Hearts', NULL, 'Breakable Heart Box', '€37', 'Heart made of White Chocolate filled with marshmallows & chopsticks. Includes 8 cakesicles.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/product-t2-1781039943586.webp?t=1781039945400', 'In Stock', 1, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, '[]'::jsonb, '{}'::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('t3', 'Cakesicles', NULL, 'Cakesicles (Box of 5)', '€17', 'Cake truffles on a stick (Minimum order). Choice of Chocolate, Vanilla, or Red Velvet flavors.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cake-sicles/cakesicles-(1).webp', 'In Stock', 1, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone),
('t4', 'Cakesicles', NULL, 'Cakesicles (Box of 10)', '€29', 'A premium box of 10 cakesicles. Choice of Chocolate, Vanilla, or Red Velvet flavors.', NULL, 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/product-images/cake-sicles/cakesicles-(3).webp', 'In Stock', 1, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, '[]'::jsonb, ARRAY['Vanilla', 'Chocolate', 'Red Velvet']::text[], '{}'::text[], '2026-05-20T15:40:56.029484+00:00'::timestamp with time zone)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  portions = EXCLUDED.portions,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  img = EXCLUDED.img,
  status = EXCLUDED.status,
  options = EXCLUDED.options,
  flavours = EXCLUDED.flavours,
  spreads = EXCLUDED.spreads;

-- 2. FEATURED ITEMS (3 items)
INSERT INTO public.featured_items (id, slot, name, description, price, img, is_empty, highlights, created_at)
VALUES
('featured-1', 1, 'Brownie Selection', 'Our most popular brownie assortment, baked fresh daily with premium chocolate.', '€xx', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/featured-images/slot-1-1781342526005.webp', FALSE, '[]'::jsonb, '2026-06-13T08:44:00.334542+00:00'::timestamp with time zone),
('featured-2', 2, 'Signature Cupcakes', 'A curated selection of our most loved cupcake flavors, perfect for any occasion.', '€xx', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/featured-images/slot-2-1781342106904.webp', FALSE, '[]'::jsonb, '2026-06-13T08:44:00.334542+00:00'::timestamp with time zone),
('featured-3', 3, 'Best Seller cake', 'Our signature masterpiece cake, loved by everyone for its perfect balance of flavor.', '€xx', 'https://pratxgdpyhqvjmszemly.supabase.co/storage/v1/object/public/featured-images/slot-3-1781342607451.webp', FALSE, '[]'::jsonb, '2026-06-13T08:44:00.334542+00:00'::timestamp with time zone)
ON CONFLICT (id) DO NOTHING;

-- 3. STORE SETTINGS
INSERT INTO public.store_settings (id, facebook_link, instagram_link, whatsapp_number, updated_at)
VALUES
(1, 'https://facebook.com/minibakes2021', 'https://instagram.com/minibakes2021', '35679820529', '2026-06-11T11:42:47.679682+00:00'::timestamp with time zone)
ON CONFLICT (id) DO NOTHING;

-- 4. STORE AVAILABILITY
INSERT INTO public.store_availability (id, is_taking_orders_today, daily_pause_message, vacation_start_date, vacation_end_date, vacation_message, updated_at)
VALUES
(1, TRUE, 'We are not taking any more orders today. Please check back tomorrow!', NULL, NULL, 'We are currently away on vacation. Check back soon!', '2026-06-13T08:03:59.687+00:00'::timestamp with time zone)
ON CONFLICT (id) DO NOTHING;

